services:
  mongo:
    image: mongo:latest
    ports:
      - 8000:27017
    command: mongod
    volumes:
      - ./data:/data/db
  server:
    build:
      context: server
    ports: 
      - 8080:8080
    depends_on:
      - mongo